#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-canal-client
  main:
    web-application-type: none
    banner-mode: console
#********************
#（★）Canal配置
#********************
cancal:
  server:
    port: 11111
  client:
    batch-size: 100